build :
  version : @project.version@
  description : "History of processing reports"
  relativePath : ${SWAGGER_RELATIVE_PATH:}
spring :
  application :
    name : reports-history
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    url : ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/lorem_ipsum_db}
    username : ${DATASOURCE_USERNAME:postgres}
    password : ${DATASOURCE_PASSWORD:postgres}
    driver-class-name : ${DATASOURCE_DRIVER:org.postgresql.Driver}
    hikari :
      pool-name : Hikari
      auto-commit : false
  jpa :
    hibernate :
      ddl-auto : none
      naming :
        physical-strategy : org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy : org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view : true
    properties :
      hibernate.jdbc.time_zone : UTC
    show-sql : false

  jackson :
    default-property-inclusion : NON_NULL
    open-in-view : true
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}
  groovy :
    template :
      check-template-location : false

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      auto-offset-reset: earliest
      properties:
        basic.auth.credentials.source : SASL_INHERIT
        security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";"
        isolation.level: read_committed
      group-id : ${KAFKA_CONSUMERS_GROUP:reports-history}
    producer:
      bootstrap-servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      properties :
        basic.auth.credentials.source : SASL_INHERIT
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512
        sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";"
    admin:
      properties :
        bootstrap.servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512
        sasl.jaas.config : "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";"

server :
  port : ${PORT:8080}
  shutdown : graceful

management :
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      path-mapping :
        health : actuator/health
        prometheus : metrics
      base-path : /
      exposure :
        include : health, prometheus
  endpoint :
    health :
      enabled : true

loremipsum :
  kafka:
    create-topics-on-startup: ${KAFKA_CREATE_TOPICS_ON_STARTUP:true}
    consumer:
      threads: ${KAFKA_CONSUMER_THREADS:4}
    topics:
      rejected-messages-topic : ${KAFKA_TOPIC_REJECTED_MESSAGES:dlq.rejected_messages}
      words-processed-topic : ${KAFKA_TOPIC_WORDS_PROCESSED:words.processed}
      words-processed-partitions : ${KAFKA_TOPIC_PARTITIONS_WORDS_PROCESSED:4}
      words-processed-retention-ms : ${KAFKA_TOPIC_RETENTION_WORDS_PROCESSED:600000}
