build :
  version : @project.version@
  description : "Words statistic generator"
  relativePath : ${SWAGGER_RELATIVE_PATH:}
spring :
  application :
    name : words-statistic
  jackson :
    default-property-inclusion : NON_NULL
    open-in-view : true
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}
  groovy :
    template :
      check-template-location : false
  kafka:
    producer:
      bootstrap-servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      properties :
        basic.auth.credentials.source : SASL_INHERIT
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512
        sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";"
    admin:
      properties :
        bootstrap.servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512
        sasl.jaas.config : "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";"

server :
  port : ${PORT:8080}
  shutdown : graceful

management :
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      path-mapping :
        health : actuator/health
        prometheus : metrics
      base-path : /
      exposure :
        include : health, prometheus
  endpoint :
    health :
      enabled : true

loremipsum :
  net-client :
    api-server-url-template: https://loripsum.net/api/{paragraphsNum}/{lengthType}
    connect-timeout: 1  # sec
    request-timeout: 2
  kafka:
    create-topics-on-startup: ${KAFKA_CREATE_TOPICS_ON_STARTUP:true}
    topics:
      words-processed-topic : ${KAFKA_TOPIC_WORDS_PROCESSED:words.processed}
      words-processed-partitions : ${KAFKA_TOPIC_PARTITIONS_WORDS_PROCESSED:4}
      words-processed-retention-ms : ${KAFKA_TOPIC_RETENTION_WORDS_PROCESSED:600000}

